allow-unwrap-in-tests = true
allow-expect-in-tests = true
allow-panic-in-tests = true
allow-print-in-tests = true
doc-valid-idents = ["TelltaleDNS", "AdGuard", "AdBlock", "NextDNS", "Pi-hole", "DoH", "DoT", "DoQ", "DNSSEC", "EDNS", "OpenAPI", "OIDC", "PKCE", "S3-FIFO", "YouTube", "DuckDuckGo", "TikTok", "DoH3", "DHCPv4", "DNSCrypt", "UniFi", "OPNsense", ".."]
