/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign in.
         * @description Username and password, plus `totp` (or `recoveryCode`) when two-factor sign-in is on:
         *     without it the answer is 401 `totp_required`. Sets an `HttpOnly; SameSite=Strict` session
         *     cookie and returns the CSRF token to send as `X-CSRF-Token` on changes. Repeated failures
         *     lock the username and the address out for a while (429).
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign out.
         * @description Ends this session and clears the cookie. With a token or Basic, does nothing but succeed.
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Who am I.
         * @description The signed-in user: role (capped by a token's scope), two-factor state, unused recovery
         *     codes, and how this request authenticated.
         */
        get: operations["get_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Change my password.
         * @description Needs the current password. Ends every other session of this user.
         */
        post: operations["change_password"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/setup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create the first admin.
         * @description Only while no user exists. `setupToken` is printed in the server log at startup and saved
         *     in `<data_dir>/setup-token`. Signs the new admin in (sets the session cookie).
         */
        post: operations["setup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Sign-in state.
         * @description Whether first-run setup is needed, and who the request is signed in as (if anyone),
         *     with the session's CSRF token. Public; the UI calls it on load.
         */
        get: operations["status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/totp/disable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Turn off two-factor sign-in.
         * @description Needs the current password. Removes the TOTP secret and the unused recovery codes.
         */
        post: operations["totp_disable"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/totp/enable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Turn on two-factor sign-in.
         * @description Confirms a current code from the app enrolled with POST /auth/totp/setup, turns
         *     enforcement on, and returns ten single-use recovery codes (shown only now).
         */
        post: operations["totp_enable"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/totp/setup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start two-factor enrollment.
         * @description Returns a new TOTP secret (base32 and an `otpauth://` URL for a QR code). Nothing is
         *     enforced until POST /auth/totp/enable confirms a code from the app.
         */
        post: operations["totp_setup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Configured clients (devices) and how they're recognized.
         * @description Each device's name, the IPs, CIDRs, MACs, or client IDs that identify it, and its groups in
         *     priority order (the first group's settings apply). Unknown devices use the `default` group.
         */
        get: operations["clients"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/explain": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Explain a decision.
         * @description Why `name` is or isn't blocked for a client: how the client is identified, its groups,
         *     every matching rule in every list (with the list line), which rule decides, and where the
         *     query would be forwarded. Example: `GET /api/v1/explain?name=ads.example.com&client=192.168.1.20`.
         */
        get: operations["explain"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Client groups, their lists, block mode, and pause state.
         * @description Groups decide which lists apply to a device and how blocked queries are answered. `lists`
         *     null means every enabled list; `pausedUntilUnixSeconds` is set while blocking is paused.
         */
        get: operations["groups"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/lists": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Filter lists and their download state.
         * @description Every configured list with its kind (block/allow), source, download state (`ok`, `failed`,
         *     `pending`) and last error, size, and how many names it contributes to the active snapshot.
         */
        get: operations["lists"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/queries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search the query log.
         * @description Newest first. Filters combine with AND: name (substring by default; `match=exact|suffix|
         *     glob|regex`), client, status, query type, response code, upstream, minimum latency, and
         *     time range. Pass `nextCursor` back as `cursor` for older rows. Example:
         *     `GET /api/v1/queries?name=doubleclick&status=blocked&from=-1h&limit=50`.
         */
        get: operations["queries"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/queries/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Live query stream.
         * @description Server-Sent Events, newest as they happen: `event: query` carries a `QueryRow` (same
         *     fields as GET /queries), `event: dropped` a `TailDropped` when matching queries were
         *     skipped (over `rate`, or this client fell behind), and a comment every 15 s keeps the
         *     connection open. Filters are applied on the server. In a browser:
         *     `new EventSource('/api/v1/queries/stream?status=blocked')` (the session cookie signs it
         *     in). Honors the query-log privacy level; at most 16 streams per node.
         */
        get: operations["queries_stream"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stats/latency": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Latency percentiles.
         * @description By answer path and transport, query type, upstream server, or the upstream stage, for the
         *     current or previous hour, in milliseconds (HDR histograms, 2 significant digits).
         */
        get: operations["stats_latency"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stats/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Totals over a time range.
         * @description Queries, blocked (count and percent), cache hits, forwarded, NXDOMAIN and SERVFAIL counts
         *     over the range (per-minute data up to 48 hours back, hourly rollups beyond), plus this
         *     hour's active clients and latency percentiles by answer path. Example:
         *     `GET /api/v1/stats/summary?from=-24h` or `?from=-30d`.
         */
        get: operations["stats_summary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stats/timeseries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Query counts over time.
         * @description Buckets by status, query type, and response code, plus upstream exchanges. `step=second`
         *     covers the last 15 minutes, `step=minute` 7 days (48 hours live), `step=hour` 400 days,
         *     `step=day` everything. Buckets without queries are omitted. Example:
         *     `GET /api/v1/stats/timeseries?from=-30d&step=hour`.
         */
        get: operations["stats_timeseries"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stats/top": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Top domains, blocked domains, NXDOMAIN names, or clients.
         * @description Ranked by a Space-Saving sketch per hour: `count` is an upper bound and `errorBound` how
         *     far it may be over. Example: `GET /api/v1/stats/top?kind=blocked&limit=10`. With
         *     `kind=domains&client=192.168.1.20`, one client's top domains (recently active clients only).
         */
        get: operations["stats_top"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/system/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Node and build information.
         * @description Version, role, uptime, listeners, whether the query log is on, and the active filter
         *     snapshot. Cheap; suitable for health dashboards.
         */
        get: operations["system_info"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tokens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * My API tokens.
         * @description Name, scope, expiry, and last use. The secrets themselves are never shown again.
         */
        get: operations["list_tokens"];
        put?: never;
        /**
         * Create an API token.
         * @description For scripts, dashboards, and agents: send as `Authorization: Bearer <token>`. `scope`
         *     `read` acts as viewer, `write` as operator, `admin` as admin, never above the owner's role.
         *     The token is shown only in this response.
         */
        post: operations["create_token"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tokens/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Revoke one of my API tokens.
         * @description By the `id` from GET /tokens. Takes effect immediately; other tokens are unaffected.
         */
        delete: operations["delete_token"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/upstreams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Upstream servers with health and latency.
         * @description Every upstream with its stable ID, endpoint, groups, circuit-breaker state (`closed` means
         *     healthy), request and failure counts, and smoothed answer time in milliseconds.
         */
        get: operations["upstreams"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Users (admin).
         * @description Every user with role, status, and two-factor state.
         */
        get: operations["list_users"];
        put?: never;
        /**
         * Add a user (admin).
         * @description `role` is `viewer`, `operator`, or `admin`. The password needs at least 10 characters.
         */
        post: operations["create_user"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete a user (admin).
         * @description Also deletes their sessions and tokens. The last enabled admin can't be deleted.
         */
        delete: operations["delete_user"];
        options?: never;
        head?: never;
        /**
         * Change a user (admin).
         * @description Role, disabled, HTTP Basic opt-in, a new password (ends their sessions), or a TOTP reset.
         *     The last enabled admin can't be demoted or disabled.
         */
        patch: operations["update_user"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Whether setup is needed and who is signed in (public). */
        AuthStatus: {
            authenticated: boolean;
            /** @description For session sign-ins: send as `X-CSRF-Token` on changes. */
            csrfToken?: string | null;
            /** @description No user exists yet: create the first admin with the setup token. */
            setupRequired: boolean;
            user?: components["schemas"]["Me"] | null;
        };
        /** @description A configured client (device). */
        ClientInfo: {
            /** @description Highest priority first. */
            groups: string[];
            /** @description IPs, CIDRs, MACs, or `id:<client-id>` this device is recognized by. */
            match: string[];
            name: string;
        };
        /**
         * @description Stable error codes.
         * @enum {string}
         */
        Code: "invalid_parameter" | "not_found" | "unsupported_scope" | "unavailable" | "internal" | "unauthorized" | "totp_required" | "forbidden" | "csrf_rejected" | "conflict" | "rate_limited";
        CreateToken: {
            /**
             * Format: int32
             * @description Default: never expires.
             */
            expiresInDays?: number | null;
            /** @description What it's for (`grafana`, `homepage-widget`). */
            name: string;
            scope?: components["schemas"]["Scope"] | null;
        };
        CreateUser: {
            /** @description Allow HTTP Basic on the API for scripts and scrapers (default false). */
            allowBasicApi?: boolean | null;
            password: string;
            role: components["schemas"]["Role"];
            username: string;
        };
        ExplainBlock: {
            /** Format: int32 */
            edeCode: number;
            list: string;
            /** @description `null_ip`, `nxdomain`, `nodata`, `refused`, or `custom_ip`. */
            mode: string;
            /** Format: int32 */
            ttlSeconds: number;
        };
        ExplainClient: {
            /** @description The configured device it was recognized as. */
            device?: string | null;
            /** @description Highest priority first. */
            groups: string[];
            /** @description `client_id`, `edns_mac`, `neighbor_mac`, `ip`, `cidr`, or `default`. */
            identifiedBy: string;
            ip: string;
            mac?: string | null;
        };
        ExplainFilter: {
            notes: string[];
            rules: components["schemas"]["ExplainRule"][];
            /** Format: int64 */
            snapshot?: number | null;
        };
        ExplainLine: {
            /** Format: int32 */
            line: number;
            text: string;
        };
        ExplainRoute: {
            /** @description Upstream group. */
            group: string;
            /** @description An explicit route matched (not just the default group). */
            routed: boolean;
        };
        ExplainRule: {
            /** @description The client's groups use this list. */
            enabled: boolean;
            /** @description `domain`, `modifier`, or `regex`. */
            kind: string;
            /** @description Where the rule is in the list. */
            lines: components["schemas"]["ExplainLine"][];
            list: string;
            /** @description The listed name that matched. */
            name?: string | null;
            /** @description `subtree`, `exact`, or `subdomains`. */
            scope?: string | null;
            /** @description `important_allow`, `important_block`, `allow`, or `block`. */
            tier: string;
            /** @description This rule decides the query. */
            winner: boolean;
        };
        /** @description Why a name is or isn't blocked for a client, and where it would go (FLT-013). */
        Explanation: {
            block?: components["schemas"]["ExplainBlock"] | null;
            client: components["schemas"]["ExplainClient"];
            filter?: components["schemas"]["ExplainFilter"] | null;
            name: string;
            notes: string[];
            /** @description `refused`, `special`, `local`, `blocked`, `allowed`, or `resolved`. */
            outcome: string;
            /**
             * Format: int64
             * @description Blocking is paused for this client until then (Unix seconds).
             */
            pausedUntilUnixSeconds?: number | null;
            qtype: string;
            route?: components["schemas"]["ExplainRoute"] | null;
            /** @description One sentence for people. */
            summary: string;
        };
        /** @description A client group. */
        GroupInfo: {
            /** @description `null_ip`, `nxdomain`, `nodata`, `refused`, or `custom_ip`. */
            blockMode: string;
            /** Format: int32 */
            blockTtlSeconds: number;
            /** @description Lists this group uses; null means every enabled list. */
            lists?: string[] | null;
            name: string;
            /**
             * Format: int64
             * @description Blocking is paused for this group until then (Unix seconds).
             */
            pausedUntilUnixSeconds?: number | null;
            /** Format: int32 */
            priority: number;
        };
        /**
         * @description Which hour a top-K or latency call reads.
         * @enum {string}
         */
        Hour: "current" | "previous";
        /** @description A list wrapper used by every collection endpoint. */
        Items_ClientInfo: {
            items: {
                /** @description Highest priority first. */
                groups: string[];
                /** @description IPs, CIDRs, MACs, or `id:<client-id>` this device is recognized by. */
                match: string[];
                name: string;
            }[];
        };
        /** @description A list wrapper used by every collection endpoint. */
        Items_GroupInfo: {
            items: {
                /** @description `null_ip`, `nxdomain`, `nodata`, `refused`, or `custom_ip`. */
                blockMode: string;
                /** Format: int32 */
                blockTtlSeconds: number;
                /** @description Lists this group uses; null means every enabled list. */
                lists?: string[] | null;
                name: string;
                /**
                 * Format: int64
                 * @description Blocking is paused for this group until then (Unix seconds).
                 */
                pausedUntilUnixSeconds?: number | null;
                /** Format: int32 */
                priority: number;
            }[];
        };
        /** @description A list wrapper used by every collection endpoint. */
        Items_LatencyRow: {
            items: {
                /** Format: int64 */
                count: number;
                /** @description What the row is for (`cache/udp`, `AAAA`, `quad9-tls-1`, `upstream`). */
                key: string;
                /** Format: double */
                maxMs: number;
                /** Format: double */
                p50Ms: number;
                /** Format: double */
                p90Ms: number;
                /** Format: double */
                p999Ms: number;
                /** Format: double */
                p99Ms: number;
            }[];
        };
        /** @description A list wrapper used by every collection endpoint. */
        Items_ListInfo: {
            items: {
                /** Format: int64 */
                bytes: number;
                enabled: boolean;
                /**
                 * Format: int64
                 * @description Names this list contributes to the active snapshot.
                 */
                entries: number;
                error?: string | null;
                /** @description `block` or `allow`. */
                kind: string;
                /** Format: int64 */
                lastChangedUnixSeconds?: number | null;
                /** Format: int64 */
                lastCheckedUnixSeconds?: number | null;
                /** Format: int64 */
                lines: number;
                name: string;
                /** @description URL, file path, or `inline`. */
                source: string;
                /** @description `ok`, `failed`, or `pending` (not downloaded yet). */
                state: string;
            }[];
        };
        /** @description A list wrapper used by every collection endpoint. */
        Items_TimeBucket: {
            items: {
                /** @description By query type (`A`, `AAAA`, ..., `other`). */
                byQtype: {
                    [key: string]: number;
                };
                /** @description By response code (`NOERROR`, `NXDOMAIN`, ...). */
                byRcode: {
                    [key: string]: number;
                };
                /** @description By status (`cached`, `forwarded`, `blocked`, ...). */
                byStatus: {
                    [key: string]: number;
                };
                /**
                 * Format: int64
                 * @description Bucket start, Unix seconds.
                 */
                startUnixSeconds: number;
                /**
                 * Format: int32
                 * @description Queries in the bucket.
                 */
                total: number;
                /** Format: int32 */
                upstreamFailures: number;
                /**
                 * Format: int32
                 * @description Upstream exchanges, and how many failed.
                 */
                upstreamQueries: number;
            }[];
        };
        /** @description A list wrapper used by every collection endpoint. */
        Items_TopItem: {
            items: {
                /** Format: int64 */
                count: number;
                /** Format: int64 */
                errorBound: number;
                /** @description Domain name or client address. */
                key: string;
                /** @description The configured device name, for clients that have one. */
                name?: string | null;
            }[];
        };
        /** @description A list wrapper used by every collection endpoint. */
        Items_UpstreamInfo: {
            items: {
                /** @description Circuit breaker: `closed` (healthy), `open` (benched), or `half_open` (probing). */
                breaker: string;
                /** @description `udp://…`, `tls://…`, `https://…`. */
                endpoint: string;
                /** Format: int64 */
                failures: number;
                /** @description Groups it belongs to. */
                groups: string[];
                /**
                 * Format: int32
                 * @description Stable ID (config order, from 1); query rows and latency rows refer to it.
                 */
                id: number;
                /**
                 * Format: double
                 * @description Smoothed answer time.
                 */
                latencyEwmaMs: number;
                name: string;
                /** Format: int64 */
                requests: number;
            }[];
        };
        /**
         * @description What `GET /stats/latency` groups by.
         * @enum {string}
         */
        LatencyBy: "path" | "qtype" | "upstream" | "stage";
        /** @description Latency percentiles for one key (HDR histogram, 2 significant digits). */
        LatencyRow: {
            /** Format: int64 */
            count: number;
            /** @description What the row is for (`cache/udp`, `AAAA`, `quad9-tls-1`, `upstream`). */
            key: string;
            /** Format: double */
            maxMs: number;
            /** Format: double */
            p50Ms: number;
            /** Format: double */
            p90Ms: number;
            /** Format: double */
            p999Ms: number;
            /** Format: double */
            p99Ms: number;
        };
        /** @description A filter list and its download state. */
        ListInfo: {
            /** Format: int64 */
            bytes: number;
            enabled: boolean;
            /**
             * Format: int64
             * @description Names this list contributes to the active snapshot.
             */
            entries: number;
            error?: string | null;
            /** @description `block` or `allow`. */
            kind: string;
            /** Format: int64 */
            lastChangedUnixSeconds?: number | null;
            /** Format: int64 */
            lastCheckedUnixSeconds?: number | null;
            /** Format: int64 */
            lines: number;
            name: string;
            /** @description URL, file path, or `inline`. */
            source: string;
            /** @description `ok`, `failed`, or `pending` (not downloaded yet). */
            state: string;
        };
        /** @description List wrapper. */
        Listed_TokenInfo: {
            items: {
                /** Format: int64 */
                createdUnixSeconds: number;
                /** Format: int64 */
                expiresUnixSeconds?: number | null;
                id: string;
                /** Format: int64 */
                lastUsedUnixSeconds?: number | null;
                name: string;
                scope: components["schemas"]["Scope"];
            }[];
        };
        /** @description List wrapper. */
        Listed_UserInfo: {
            items: {
                allowBasicApi: boolean;
                /** Format: int64 */
                createdUnixSeconds: number;
                disabled: boolean;
                /** Format: int64 */
                id: number;
                role: components["schemas"]["Role"];
                totpEnabled: boolean;
                username: string;
            }[];
        };
        LoginRequest: {
            password: string;
            /** @description A recovery code instead of `totp`. */
            recoveryCode?: string | null;
            /** @description 6-digit code from the authenticator app, when TOTP is on. */
            totp?: string | null;
            username: string;
        };
        LoginResponse: {
            /** @description Send as `X-CSRF-Token` on every change made with this session. */
            csrfToken: string;
            /** Format: int64 */
            expiresUnixSeconds: number;
            user: components["schemas"]["Me"];
        };
        /** @description The signed-in user. */
        Me: {
            allowBasicApi: boolean;
            /** Format: int64 */
            id: number;
            /**
             * Format: int64
             * @description Unused recovery codes (when TOTP is on).
             */
            recoveryCodesLeft: number;
            /** @description Effective role (a token's scope caps its owner's role). */
            role: components["schemas"]["Role"];
            totpEnabled: boolean;
            username: string;
            /** @description How this request authenticated: `session`, `token`, or `basic`. */
            via: string;
        };
        /**
         * @description How `name` in [`QueryParams`] is matched.
         * @enum {string}
         */
        NameMatch: "substring" | "exact" | "suffix" | "glob" | "regex";
        NewToken: {
            info: components["schemas"]["TokenInfo"];
            /** @description The token, shown only now: send as `Authorization: Bearer <token>`. */
            token: string;
        };
        PasswordChange: {
            currentPassword: string;
            newPassword: string;
        };
        PasswordConfirm: {
            password: string;
        };
        /**
         * @description An API error.
         * @example {
         *       "code": "invalid_parameter",
         *       "detail": "`from`: `yesterday`: expected RFC 3339 time (2026-10-03T12:00:00Z) or a relative offset (-24h)",
         *       "hint": "Use a relative offset such as -24h, or RFC 3339 such as 2026-10-03T00:00:00Z.",
         *       "status": 400,
         *       "title": "Invalid parameter",
         *       "type": "https://telltaledns.dev/problems/invalid_parameter"
         *     }
         */
        Problem: {
            /** @description Stable machine-readable code. */
            code: components["schemas"]["Code"];
            /** @description What went wrong in this request. */
            detail: string;
            /** @description What to do about it. */
            hint?: string | null;
            /**
             * Format: int32
             * @description HTTP status code.
             */
            status: number;
            /** @description Short, human-readable summary of the problem type. */
            title: string;
            /** @description URI identifying the problem type. */
            type: string;
        };
        /** @description A page of query-log rows, newest first. */
        QueryPage: {
            items: components["schemas"]["QueryRow"][];
            /** @description Pass as `cursor` to get older rows; absent when there are none. */
            nextCursor?: string | null;
            /** @description How much of the log this page looked at. */
            scanned: components["schemas"]["ScanStats"];
        };
        /** @description One logged query. */
        QueryRow: {
            /** Format: int32 */
            answers: number;
            /** @description Client address. */
            client: string;
            /** @description The configured device name, when known. */
            clientName?: string | null;
            /** @description The client's primary group. */
            group?: string | null;
            /** @description The list whose rule blocked or allowed the query. */
            list?: string | null;
            name: string;
            proto: string;
            qtype: string;
            /** @description Response code, or null when nothing was sent. */
            rcode?: string | null;
            /** Format: int32 */
            responseBytes: number;
            /** @description `domain`, `modifier`, `regex`, `cname`, or `allow`. */
            rule?: string | null;
            status: string;
            /** @description When the query arrived (RFC 3339, milliseconds). */
            time: string;
            /** Format: double */
            totalMs: number;
            /** Format: int64 */
            tsUnixMicros: number;
            /** Format: double */
            upstreamMs: number;
        };
        /** @description Single-use recovery codes, shown once. */
        RecoveryCodes: {
            codes: string[];
        };
        /**
         * @description What a user may do (`spec/08` §6).
         * @enum {string}
         */
        Role: "viewer" | "operator" | "admin";
        ScanStats: {
            blocksRead: number;
            blocksTotal: number;
            rowsScanned: number;
            segments: number;
        };
        /**
         * @description An API token's scope; a token never exceeds its owner's role.
         * @enum {string}
         */
        Scope: "read" | "write" | "admin";
        SetupRequest: {
            /** @description At least 10 characters. */
            password: string;
            /** @description From the server log or `<data_dir>/setup-token`. */
            setupToken: string;
            username: string;
        };
        /**
         * @description Time-bucket size for [`TimeseriesParams`].
         * @enum {string}
         */
        Step: "second" | "minute" | "hour" | "day";
        /** @description Totals over a time range. */
        Summary: {
            /**
             * Format: int64
             * @description Distinct clients seen this hour.
             */
            activeClients: number;
            /** Format: int64 */
            blocked: number;
            /**
             * Format: double
             * @description Blocked share of all queries, 0–100.
             */
            blockedPercent: number;
            /**
             * Format: double
             * @description Cache share of answered queries that weren't blocked or local, 0–100.
             */
            cacheHitPercent: number;
            /**
             * Format: int64
             * @description Answered from cache (fresh or stale).
             */
            cached: number;
            /** Format: int64 */
            forwarded: number;
            /** Format: int64 */
            fromUnixSeconds: number;
            /** @description Latency percentiles this hour, by answer path (`cache`, `upstream`, ...). */
            latency: components["schemas"]["LatencyRow"][];
            /** Format: int64 */
            nxdomain: number;
            /** Format: int64 */
            queries: number;
            /** Format: int64 */
            servfail: number;
            /** Format: int64 */
            toUnixSeconds: number;
        };
        /** @description Node and build information. */
        SystemInfo: {
            /**
             * Format: int64
             * @description Blocked names in the active snapshot.
             */
            filterNames: number;
            /**
             * Format: int64
             * @description Version of the active filter snapshot, if one is loaded.
             */
            filterSnapshot?: number | null;
            /** @description DNS listeners, as `proto://addr`. */
            listeners: string[];
            /** @description Node name. */
            node: string;
            /** @description Whether the per-query log is being written. */
            queryLog: boolean;
            /** @description Process role: `all`, `resolver`, or `controller`. */
            role: string;
            /** @description When the process started (RFC 3339). */
            startedAt: string;
            /** Format: int64 */
            uptimeSeconds: number;
            /**
             * @description TelltaleDNS version.
             * @example 0.1.0
             */
            version: string;
        };
        /** @description Sent as an SSE `dropped` event when matching queries weren't delivered. */
        TailDropped: {
            /**
             * Format: int64
             * @description How many matching queries were skipped since the last report.
             */
            dropped: number;
            /** @description `rate`: over this subscriber's `rate`; `lag`: the subscriber fell behind. */
            reason: string;
        };
        /** @description Counts for one time bucket. */
        TimeBucket: {
            /** @description By query type (`A`, `AAAA`, ..., `other`). */
            byQtype: {
                [key: string]: number;
            };
            /** @description By response code (`NOERROR`, `NXDOMAIN`, ...). */
            byRcode: {
                [key: string]: number;
            };
            /** @description By status (`cached`, `forwarded`, `blocked`, ...). */
            byStatus: {
                [key: string]: number;
            };
            /**
             * Format: int64
             * @description Bucket start, Unix seconds.
             */
            startUnixSeconds: number;
            /**
             * Format: int32
             * @description Queries in the bucket.
             */
            total: number;
            /** Format: int32 */
            upstreamFailures: number;
            /**
             * Format: int32
             * @description Upstream exchanges, and how many failed.
             */
            upstreamQueries: number;
        };
        TokenInfo: {
            /** Format: int64 */
            createdUnixSeconds: number;
            /** Format: int64 */
            expiresUnixSeconds?: number | null;
            id: string;
            /** Format: int64 */
            lastUsedUnixSeconds?: number | null;
            name: string;
            scope: components["schemas"]["Scope"];
        };
        /**
         * @description One ranked item. Counts come from a Space-Saving sketch: the true count lies in
         *     `[count - errorBound, count]`.
         */
        TopItem: {
            /** Format: int64 */
            count: number;
            /** Format: int64 */
            errorBound: number;
            /** @description Domain name or client address. */
            key: string;
            /** @description The configured device name, for clients that have one. */
            name?: string | null;
        };
        /**
         * @description What a top-K list ranks.
         * @enum {string}
         */
        TopKind: "domains" | "blocked" | "nxdomain" | "clients";
        TotpCode: {
            code: string;
        };
        TotpSetup: {
            /** @description For a QR code. */
            otpauthUrl: string;
            /** @description For manual entry in an authenticator app. */
            secretBase32: string;
        };
        UpdateUser: {
            allowBasicApi?: boolean | null;
            disabled?: boolean | null;
            /** @description Set a new password (ends the user's sessions). */
            password?: string | null;
            /** @description Turn off the user's TOTP (if they lost their device). */
            resetTotp?: boolean | null;
            role?: components["schemas"]["Role"] | null;
        };
        /** @description An upstream server and its health. */
        UpstreamInfo: {
            /** @description Circuit breaker: `closed` (healthy), `open` (benched), or `half_open` (probing). */
            breaker: string;
            /** @description `udp://…`, `tls://…`, `https://…`. */
            endpoint: string;
            /** Format: int64 */
            failures: number;
            /** @description Groups it belongs to. */
            groups: string[];
            /**
             * Format: int32
             * @description Stable ID (config order, from 1); query rows and latency rows refer to it.
             */
            id: number;
            /**
             * Format: double
             * @description Smoothed answer time.
             */
            latencyEwmaMs: number;
            name: string;
            /** Format: int64 */
            requests: number;
        };
        UserInfo: {
            allowBasicApi: boolean;
            /** Format: int64 */
            createdUnixSeconds: number;
            disabled: boolean;
            /** Format: int64 */
            id: number;
            role: components["schemas"]["Role"];
            totpEnabled: boolean;
            username: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Signed out. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
        };
    };
    change_password: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordChange"];
            };
        };
        responses: {
            /** @description Changed. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    setup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetupRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Setup is already done. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    status: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthStatus"];
                };
            };
        };
    };
    totp_disable: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordConfirm"];
            };
        };
        responses: {
            /** @description Off. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    totp_enable: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TotpCode"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecoveryCodes"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    totp_setup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TotpSetup"];
                };
            };
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    clients: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Items_ClientInfo"];
                };
            };
        };
    };
    explain: {
        parameters: {
            query: {
                /**
                 * @description The name to explain.
                 * @example ads.example.com
                 */
                name: string;
                /** @description The client's IP address. Default: 127.0.0.1. */
                client?: string;
                /** @description Query type. Default: `A`. */
                qtype?: string;
                /** @description The client's MAC address (default: from the neighbor table). */
                mac?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Explanation"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    groups: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Items_GroupInfo"];
                };
            };
        };
    };
    lists: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Items_ListInfo"];
                };
            };
        };
    };
    queries: {
        parameters: {
            query?: {
                /** @description Name to look for; see `match`. */
                name?: string;
                /** @description How to match `name`. Default: `substring`. */
                match?: components["schemas"]["NameMatch"];
                /** @description Client IP address. */
                client?: string;
                /** @description Statuses, comma-separated (`blocked,forwarded`). */
                status?: string;
                /** @description Query types, comma-separated (`A,AAAA`). */
                qtype?: string;
                /** @description Response codes, comma-separated (`NXDOMAIN,SERVFAIL`). */
                rcode?: string;
                /** @description Upstream ID. */
                upstream?: number;
                /** @description Only queries that took at least this long. */
                minLatencyMs?: number;
                /** @description Start: RFC 3339 or relative (`-1h`). Default: no limit. */
                from?: string;
                /** @description End. Default: now. */
                to?: string;
                /** @description Rows per page (1–1000, default 100). */
                limit?: number;
                /** @description Continue after a previous page (`nextCursor` from it). */
                cursor?: string;
                /** @description `cluster` (default) or `node:local`. */
                scope?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueryPage"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description The query log is off. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    queries_stream: {
        parameters: {
            query?: {
                /** @description Name to look for; see `match`. */
                name?: string;
                /** @description How to match `name`: `substring` (default), `exact`, `suffix`, or `glob` (`*`, `?`). */
                match?: components["schemas"]["NameMatch"];
                /** @description Client IP address. */
                client?: string;
                /** @description The client's group (its highest-priority group). */
                group?: string;
                /** @description Statuses, comma-separated (`blocked,forwarded`). */
                status?: string;
                /** @description Query types, comma-separated (`A,AAAA`). */
                qtype?: string;
                /** @description Upstream ID (from `GET /upstreams`). */
                upstream?: number;
                /** @description Only queries that took at least this long. */
                minLatencyMs?: number;
                /**
                 * @description Most events per second sent to this subscriber (1–2000, default 500). The rest are
                 *     counted and reported in `dropped` events.
                 */
                rate?: number;
                /** @description `cluster` (default) or `node:local`. */
                scope?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description `text/event-stream` of `query` (QueryRow) and `dropped` (TailDropped) events. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    stats_latency: {
        parameters: {
            query: {
                by: components["schemas"]["LatencyBy"];
                /** @description Default: `current`. */
                hour?: components["schemas"]["Hour"];
                /** @description `cluster` (default) or `node:local`. */
                scope?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Items_LatencyRow"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    stats_summary: {
        parameters: {
            query?: {
                /**
                 * @description Start: RFC 3339 or relative (`-24h`, `-30d`). Default: 24 hours ago. Ranges over
                 *     48 hours are summed from hourly rollups.
                 */
                from?: string;
                /** @description End. Default: now. */
                to?: string;
                /** @description `cluster` (default) or `node:local`. */
                scope?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Summary"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    stats_timeseries: {
        parameters: {
            query?: {
                /**
                 * @description Start: RFC 3339 or relative (`-1h`). Default: 5 minutes ago (second steps), 1 hour
                 *     (minute), 7 days (hour), or 90 days (day).
                 */
                from?: string;
                /** @description End: RFC 3339 or relative. Default: now. */
                to?: string;
                /** @description Bucket size. Default: `minute`. */
                step?: components["schemas"]["Step"];
                /** @description `cluster` (default) or `node:local`. */
                scope?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Items_TimeBucket"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    stats_top: {
        parameters: {
            query: {
                kind: components["schemas"]["TopKind"];
                /** @description Items to return (1–100, default 10). */
                limit?: number;
                /** @description Default: `current`. */
                hour?: components["schemas"]["Hour"];
                /** @description Only this client's domains (an IP address; `kind=domains` only). */
                client?: string;
                /** @description `cluster` (default) or `node:local`. */
                scope?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Items_TopItem"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    system_info: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemInfo"];
                };
            };
        };
    };
    list_tokens: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Listed_TokenInfo"];
                };
            };
        };
    };
    create_token: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateToken"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NewToken"];
                };
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    delete_token: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Token ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Revoked. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    upstreams: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Items_UpstreamInfo"];
                };
            };
        };
    };
    list_users: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Listed_UserInfo"];
                };
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    create_user: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUser"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserInfo"];
                };
            };
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    delete_user: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description User ID */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    update_user: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description User ID */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUser"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserInfo"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
}
