#!/usr/bin/env bash
# REQ: OBS-016 (ADR-105) — renders the Helm chart's SLO rule group as a plain Prometheus rules
# file for Docker Compose, Pi, and systemd installs, so both come from one template.
#
#   deploy/prometheus/build.sh           # writes deploy/prometheus/telltale-slo-rules.yaml
#   deploy/prometheus/build.sh --check   # fails if the committed file is stale
#
# The rules select job="telltale-metrics"; name your scrape job that (or edit the selector).
set -euo pipefail
here="$(cd "$(dirname "$0")" && pwd)"
out="$here/telltale-slo-rules.yaml"
helm="${HELM:-helm}"
rendered="$("$helm" template telltale "$here/../helm/telltale" \
  --set prometheusRule.enabled=true --set fullnameOverride=telltale \
  --show-only templates/monitoring.yaml)"
body="$(printf '%s\n' "$rendered" | python3 -c '
import sys, yaml
def text(dumper, data):
    style = "|" if "\n" in data else None
    return dumper.represent_scalar("tag:yaml.org,2002:str", data, style=style)
yaml.add_representer(str, text, Dumper=yaml.SafeDumper)
for doc in yaml.safe_load_all(sys.stdin):
    if doc and doc.get("kind") == "PrometheusRule":
        groups = [g for g in doc["spec"]["groups"] if g["name"] == "telltale-slo"]
        print(yaml.safe_dump({"groups": groups}, sort_keys=False, width=200), end="")
')"
text="# Generated by deploy/prometheus/build.sh from the Helm chart (prometheusRule.slo). Do not edit.
# TelltaleDNS service-level objectives (OBS-016): availability 99.9% (answers that aren't
# SERVFAIL), latency 99% within 250 ms, as in the default [slo] section. Load it with
# rule_files in prometheus.yml; the scrape job must be named telltale-metrics.
$body"
if [ "${1:-}" = "--check" ]; then
  if [ ! -f "$out" ] || [ "$(cat "$out")" != "$text" ]; then
    echo "$out is stale: run deploy/prometheus/build.sh" >&2
    exit 1
  fi
  echo "telltale-slo-rules.yaml OK"
else
  printf '%s\n' "$text" > "$out"
  echo "wrote $out"
fi
