{{- if and (include "telltale.scaled" .) (not .Values.cluster.bootstrapSecret.existingSecret) }}
{{- $name := include "telltale.clusterSecret" . }}
{{- $old := lookup "v1" "Secret" .Release.Namespace $name }}
# REQ: CLU-009 — the shared join secret for resolver pods (created once, kept on upgrade).
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}
  labels:
    {{- include "telltale.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
data:
  {{ .Values.cluster.bootstrapSecret.key }}: {{ if $old }}{{ index $old.data .Values.cluster.bootstrapSecret.key }}{{ else }}{{ randAlphaNum 48 | b64enc }}{{ end }}
{{- end }}
